version: "3.4"
services:
  api:
    build:
      context: .
    image: trsp400/creative-code-api:latest
    command: yarn dev:server
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=creative-code-db
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - WAIT_HOSTS=database:5432
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:12
    restart: always
    volumes:
      - ./db-data/mysql:/var/lib/mysql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=creative-code-db
    ports:
      - 5432:5432
