FROM node:12.7-slim

WORKDIR /app

ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV CORE_MYSQL_USER=${CORE_MYSQL_USER}
ENV CORE_MYSQL_PASSWORD=${CORE_MYSQL_PASSWORD}
ENV CORE_MYSQL_DATABASE=${CORE_MYSQL_DATABASE}
ENV CORE_MYSQL_HOST=${CORE_MYSQL_HOST}
ENV CORE_MYSQL_PORT=${CORE_MYSQL_PORT}
ENV CORE_MYSQL_POOL_MIN=${CORE_MYSQL_POOL_MIN}
ENV CORE_MYSQL_POOL_MAX=${CORE_MYSQL_POOL_MAX}
ENV PREFIX_PATH=${PREFIX_PATH}

COPY ./package*.json ./

RUN yarn

COPY ./ ./

EXPOSE 3333

CMD [ "yarn", "start"]